services:
  sam2_realtime:
    build:
      context: ../..                        
      dockerfile: models/sam2_realtime/docker/Dockerfile
    image: sam2_realtime

    gpus: all

    ports:
      - "${SAM2_REALTIME_PORT:-8000}:${SAM2_REALTIME_PORT:-8000}"

    volumes:
      - ../..:/app:rw
      - ../../cache:/cache:rw
      - ./docker/include/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro

    environment:
      - SAM2_REALTIME_PORT=${SAM2_REALTIME_PORT:-8000}
      - SAM2_REALTIME_TOKEN=${SAM2_REALTIME_TOKEN}
      - SAM2_REALTIME_PRELOAD_FLAVOR=${SAM2_REALTIME_PRELOAD_FLAVOR:-}

    command: >
      sh -c '
        exec sam2_realtime-server \
          --host 0.0.0.0 \
          --port ${SAM2_REALTIME_PORT} \
          --token "${SAM2_REALTIME_TOKEN}" \
          ${SAM2_REALTIME_PRELOAD_FLAVOR:+--preload_flavor "${SAM2_REALTIME_PRELOAD_FLAVOR}"}
      '